apiVersion: v1
kind: Pod
metadata:
  name: pvc-debug-tumido
spec:
  containers:
  - name: pvc-inspector
    image: registry.access.redhat.com/ubi9/toolbox
    command: ["sh", "-c", "sleep infinity"]
    workingDir: /pvc
    volumeMounts:
    - mountPath: /pvc
      name: pvc-volume
  volumes:
  - name: pvc-volume
    persistentVolumeClaim:
      claimName: CHANGE_ME

