#! /usr/bin/env sh
# this is a example of .lessfilter, you can change it
mime=$(file -bL --mime-type "$1")
category=${mime%%/*}
kind=${mime##*/}

if [ -d "$1" ]; then
	eza --git -hl --color=always --icons "$1"
elif [ "$kind" = pdf ] || [ "$kind" = x-xcf ]; then
	magick $1[0] jpeg:- | chafa - 
	exiftool "$1"
elif [ "$category" = image ]; then
	chafa "$1"
	exiftool "$1"
elif [ "$category" = video ]; then
	ffmpeg -i "$1" -f image2 -ss 00:00:01.000 -v -8 - | chafa -s 80x150 --color-extractor median -
	exiftool "$1"
elif [ "$kind" = vnd.openxmlformats-officedocument.spreadsheetml.sheet ] || \
	[ "$kind" = vnd.ms-excel ]; then
	in2csv "$1" | xsv table | bat -ltsv --color=always
elif [ "$category" = text ]; then
	bat --color=always "$1"
else
	#lesspipe.sh "$1" | bat --color=always
	bat --color=always "$1"
fi
# lesspipe.sh don't use exa, bat and chafa, it use ls and exiftool. so we create a lessfilter.
