root:
  askformore: false
  autoclip: false
  autoprint: false
  autoimport: true
  autosync: false
  check_recipient_hash: false
  cliptimeout: 45
  concurrency: 1
  editrecipients: false
  exportkeys: true
  nocolor: false
  noconfirm: true
  nopager: false
  notifications: true
  path: gpgcli-gitcli-fs+file:///home/tcoufal/.password-store
  recipient_hash:
    .gpg-id: 3078313441433136414338413735363442360aa69f73cca23a9ac5c8b567dc185a756e97c982164fe25859e0d1dcc1475c80a615b2123af1f5f94c11e3e9402c3ac558f500199d95b6d3e301758586281dcd26
  safecontent: false
  usesymbols: false
mounts:
  AICoE:
    askformore: false
    autoclip: false
    autoprint: false
    autoimport: true
    autosync: false
    check_recipient_hash: false
    cliptimeout: 45
    concurrency: 1
    editrecipients: false
    exportkeys: true
    nocolor: false
    noconfirm: true
    nopager: false
    notifications: true
    path: gpgcli-gitcli-fs+file:///home/tcoufal/.local/share/gopass/stores/AICoE
    recipient_hash:
      .gpg-id: 3078313441433136414338413735363442360aa69f73cca23a9ac5c8b567dc185a756e97c982164fe25859e0d1dcc1475c80a615b2123af1f5f94c11e3e9402c3ac558f500199d95b6d3e301758586281dcd26
    safecontent: false
    usesymbols: false
